"""games migration

Revision ID: 1adbb6f64a75
Revises: ffdc0a98111c
Create Date: 2021-08-24 16:41:13.898321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1adbb6f64a75'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('igdbId', sa.Integer(), nullable=False),
    sa.Column('cover_url', sa.String(length=255), nullable=False),
    sa.Column('first_release_date', sa.Integer(), nullable=False),
    sa.Column('genre', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=70), nullable=False),
    sa.Column('platforms', sa.String(length=255), nullable=False),
    sa.Column('storyline', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
