"""add column date to review

Revision ID: 6e063bf1c7b6
Revises: a0054affb70c
Create Date: 2022-02-10 16:46:30.298913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e063bf1c7b6'
down_revision = 'a0054affb70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'date')
    # ### end Alembic commands ###
